<a href="https://colab.research.google.com/github/TheThirdKnife/Student/blob/main/%D0%9B%D0%BE%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F%20%D1%80%D0%B5%D0%B3%D1%80%D0%B5%D1%81%D1%81%D0%B8%D1%8F%20(Train).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Импортируем библиотеки
import pandas as pd

# Загружаем набор данных
ECommerce_Shipping_Data = pd.read_csv('/content/drive/MyDrive/ECommerce_Shipping_Data.csv')
ECommerce_Shipping_Data.head()

ID Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0   1               D           Flight                    4                2   
1   2               F           Flight                    4                5   
2   3               A           Flight                    2                2   
3   4               B           Flight                    3                3   
4   5               C           Flight                    2                2   

   Cost_of_the_Product  Prior_purchases Product_importance Gender  \
0                  177                3                low      F   
1                  216                2                low      M   
2                  183                4                low      M   
3                  176                4             medium      M   
4                  184                3             medium      F   

   Discount_offered  Weight_in_gms  Reached_on_Time_Y_N  
0                44           1233                    1  
1                59           3088                    1  
2                48           3374                    1  
3                10           1177                    1  
4                46           2484                    1

In [5]:
# Сохраняем в новый фрейм данных столбцы предикторов
X=ECommerce_Shipping_Data.drop(['Reached_on_Time_Y_N'], axis=1)
# Сохраняем в переменную y отклик
y=ECommerce_Shipping_Data.Reached_on_Time_Y_N

In [6]:
# Преобразуем категориальные переменные в dummy
X=pd.get_dummies(X, drop_first=True)

In [7]:
from sklearn.linear_model import LogisticRegression
lorg = LogisticRegression()
lorg.fit(X, y)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [8]:
lorg.coef_

array([[-1.42079131e-04,  2.33532914e-02,  6.84565043e-02,
         1.56129394e-03, -2.16230515e-02,  1.05547944e-01,
        -1.00310549e-04,  1.80800155e-02,  1.12881988e-02,
         1.43162913e-02,  1.72531879e-02,  3.16890494e-03,
         3.33324210e-02,  1.63873436e-02,  1.50538421e-03,
         4.35508345e-02]])

In [9]:
lorg.intercept_

array([0.0561914])

In [10]:
lorg.score(X, y)

0.6569688153468497

In [11]:
import numpy as np
np.array(lorg.coef_).flatten()

array([-1.42079131e-04,  2.33532914e-02,  6.84565043e-02,  1.56129394e-03,
       -2.16230515e-02,  1.05547944e-01, -1.00310549e-04,  1.80800155e-02,
        1.12881988e-02,  1.43162913e-02,  1.72531879e-02,  3.16890494e-03,
        3.33324210e-02,  1.63873436e-02,  1.50538421e-03,  4.35508345e-02])

In [12]:
klogr = pd.DataFrame()
klogr['name']=X.columns
klogr['coef']=np.array(lorg.coef_).flatten()
klogr

name      coef
0                          ID -0.000142
1         Customer_care_calls  0.023353
2             Customer_rating  0.068457
3         Cost_of_the_Product  0.001561
4             Prior_purchases -0.021623
5            Discount_offered  0.105548
6               Weight_in_gms -0.000100
7           Warehouse_block_B  0.018080
8           Warehouse_block_C  0.011288
9           Warehouse_block_D  0.014316
10          Warehouse_block_F  0.017253
11      Mode_of_Shipment_Road  0.003169
12      Mode_of_Shipment_Ship  0.033332
13     Product_importance_low  0.016387
14  Product_importance_medium  0.001505
15                   Gender_M  0.043551

In [13]:
lorg.predict(X)

array([1, 1, 1, ..., 0, 0, 0])

In [14]:
lorg.predict_proba(X)

array([[0.00637494, 0.99362506],
       [0.00113458, 0.99886542],
       [0.00534411, 0.99465589],
       ...,
       [0.61741756, 0.38258244],
       [0.70034121, 0.29965879],
       [0.61081702, 0.38918298]])